name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: pip install pytest flask-testing

      - name: Run unit test
        run: pytest

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0'
          format: 'json'
          output: 'trivy-results.sarif'

      - name: Upload Trivy SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy-results.sarif
          retention-days: 14


